config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html
  resources :messages, only: :create
  resource :session, only: :destroy

  mount ActionCable.server => '/cable'

  root to: 'groups#show'
end

app/models/group.rb
# frozen_string_literal: true

# A chat group
class Group
  USERS_LIMIT = 10

  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Geospatial

  field :location, type: Point, sphere: true

  embeds_many :messages
  has_many :users, dependent: :destroy

  # TODO: not happy with this naming
  scope(:with_space, -> { where :users_count.lte => USERS_LIMIT })
  scope(:with_location, -> { where :location.ne => nil })
end

app/models/location.rb
# frozen_string_literal: true

# Location somewhere on earth
class Location
  include ActiveModel::AttributeMethods
  include ActiveModel::Validations

  define_attribute_methods :latitude, :longitude
  attr_accessor :latitude, :longitude
  validates :latitude, :longitude, presence: true

  def to_a
    [latitude, longitude]
  end

  def to_qry
    { latitude: latitude.to_f, longitude: longitude.to_f }
  end

  def to_json
    return nil unless valid?
    { type: 'Point', coordinates: to_a }
  end
  alias to_geo_json to_json
end

app/models/message.rb
# frozen_string_literal: true

# A chat message
class Message
  include Mongoid::Document
  include Mongoid::Timestamps

  field :content, type: String
  field :username, type: String

  embedded_in :group

  validates :content, :username, presence: true

  after_create :publish

  private

  def publish
    MessagesChannel.broadcast_to group, self
  end
end

app/models/user.rb
# frozen_string_literal: true

# User ready to chat
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  belongs_to :group, counter_cache: true, optional: true

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Base Application Controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_user

  private

  def set_user
    @user = AuthenticationService.new(cookies.signed).user
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

# Groups Controller

# Groups Controller
class GroupsController < ApplicationController
  def show; end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

# Messages Controller
class MessagesController < ApplicationController
  def create
    @message = messages.new message_params.merge(username: @user.name)
    if @message.save!
      head :created
    else
      head :bad_request
    end
  end

  private

  def message_params
    params.require(:message).permit :content
  end

  def messages
    @user.group.messages
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# Sessions Controller
class SessionsController < ApplicationController
  def destroy
    cookies.clear
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Base Application Helper
module ApplicationHelper
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

# Groups Helper
module GroupsHelper
end

app/views/groups/_debug.html.erb
<div class="sidebar__section sidebar--devTools">
    <h4 class="sidebar__section-title">
        Session
    </h4>
    <div class="sidebar__section-text">
         { user_id: <%= cookies.signed[:user_id] %> }
    </div>
</div>

app/views/groups/show.html.erb
<div class="main-bar">
    <div class="main-bar__navigation">
        <a href="#" class="main-bar__action-text">Change Room</a>
    </div>

    <div class="main-bar__username">
        <%= @user.name %>
    </div>

    <div class="main-bar__navigation">
        <%= link_to 'Logout', session_path, method: :delete, class: 'signout main-bar__action-text' %>
    </div>
</div>

<div class="app">

    <div class="sidebar sidebar--online-users">
        <div class="sidebar__section">
            <h4 class="sidebar__section-title">Online users</h4>
            <div class="sidebar__user-list">
                <a class="sidebar__user-link" href="#">Ultra Thundra Brain</a>
                <a class="sidebar__user-link" href="#">Doctor Redeemer X</a>
                <a class="sidebar__user-link sidebar__user-link--away" href="#">Mr Blade</a>
            </div>
        </div>
    </div>

    <div id="chat">
        loading...
    </div>
    
    <div class="sidebar sidebar--dev-tools">
        <%= render partial: 'debug' if Rails.env.development? %>
    </div>
</div>

<%= javascript_pack_tag 'chat' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeoChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>